# Numpy - Numerical Python

### **코드로 방정식 표현하기**

![img](./assets/numpy01/img01.png)

In [2]:
coefficient_matrix = [[2,2,1], [2,-1,2], [1,-1,2]]
constant_vector = [9,6,5]

# 그 외 여러가지 산술방식이 있음! dot product, norm, etc...

In [3]:
import numpy as np

In [4]:
test_array = np.array([1,2,3,4], float)
print(test_array)
type(test_array[3])

# npdarray 객체
# 하나의 데이터 type만 넣을 수 있다.
# dynamic typing not supported!!!


[1. 2. 3. 4.]


numpy.float64

In [5]:
a = [1,2,3,4,5]
b = [5,4,3,2,1]

a[0] is b[-1]


True

In [6]:
a = np.array(a)
b = np.array(b)

a[0] is b[-1]

False

In [7]:
test_array.dtype

dtype('float64')

In [8]:
tt = np.array([1,2,3,4], float)
print(tt.shape)
print(tt.dtype)
print(type(tt))

(4,)
float64
<class 'numpy.ndarray'>


![img2](./assets/numpy01/img02.png)

In [9]:
matrix = [[1,2,3,4], [1,2,3,4], [1,2,3,4]]
np.array(matrix, int).shape

(3, 4)

In [10]:
third = [[[1,2,3,4], [1,2,3,4], [1,2,3,4]],[[1,2,3,4], [1,2,3,4], [1,2,3,4]],[[1,2,3,4], [1,2,3,4], [1,2,3,4]],[[1,2,3,4], [1,2,3,4], [1,2,3,4]]]

print(np.array(third, np.int64).ndim) # 사실 rank와 같다!
print(np.array(third, np.int64).shape)
print(np.array(third, np.int64).size) # data 요소의 개수 4 x 3 x 4
print(np.array(third, np.int64).nbytes) # ndarray object의 메모리 크기!!! --> 나중에 파라미터 크기에 관련됨 
# 64bit, 8byte * 48

3
(4, 3, 4)
48
384


![img3](./assets/numpy01/img3.png)

In [11]:
# reshape
aa = [[1,2,3,4], [1,2,3,4]]
print(np.array(aa).shape)
print(np.array(aa))
print()
print(np.array(aa).reshape(8,).shape)
print(np.array(aa).reshape(8,))
print()
print(np.array(aa).reshape(-1,2).shape) # -1은 size를 기반으로 row개수를 자동산출해준다.
print(np.array(aa).reshape(-1,2))

(2, 4)
[[1 2 3 4]
 [1 2 3 4]]

(8,)
[1 2 3 4 1 2 3 4]

(4, 2)
[[1 2]
 [3 4]
 [1 2]
 [3 4]]


![img4](./assets/numpy01/img04.png)

In [12]:
ff = [[1,2,3,4,],[2,4,6,8],[3,6,9,12]]
ff = np.array(ff)
print(ff.shape)
print(ff)
print(ff.flatten())

(3, 4)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]]
[ 1  2  3  4  2  4  6  8  3  6  9 12]


In [13]:
ff[:,:]

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [14]:
ff[:,2:]

array([[ 3,  4],
       [ 6,  8],
       [ 9, 12]])

In [15]:
ff[1:,:]

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [16]:
a = np.arange(100).reshape(10, 10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [17]:
a[:-1]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [18]:
a[:,::2]

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [19]:
a[::2,::3]

array([[ 0,  3,  6,  9],
       [20, 23, 26, 29],
       [40, 43, 46, 49],
       [60, 63, 66, 69],
       [80, 83, 86, 89]])

### Creation Function

In [20]:
# arange
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [21]:
np.arange(0, 5, 0.5) # floating point 가능!

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [22]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [23]:
# zeros
np.zeros(shape=(10,), dtype=np.int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
# ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
# empty
# shape만 주어지고 비어있는 ndarray  생성
# memory initialization 안됨!!!
np.empty(shape=(10, ), dtype=np.int8)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [26]:
np.empty((3,6))

array([[1.24842706e-316, 0.00000000e+000, 6.93866741e-310,
        6.93866551e-310, 6.93866521e-310, 6.93866517e-310],
       [6.93866521e-310, 6.93866525e-310, 6.93866551e-310,
        6.93866517e-310, 6.93866719e-310, 6.93866521e-310],
       [6.93866525e-310, 6.93866517e-310, 6.93866526e-310,
        6.93866687e-310, 6.93866517e-310, 6.93866523e-310]])

In [27]:
# something_like
test = np.arange(30).reshape(5,6)
np.ones_like(test)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [28]:
np.empty_like(test)

array([[            14445784,                    0,  8214565722428407808,
              82952998354994, -9191283889509535232,          40567308288],
       [     688294279038834,  8214565722394853376,        4887672782849,
          637822297226703360,  7305804402566194515,     9132543580309106],
       [ 8214565720868126720,       36773509988384,  8459008515057965568,
         8286623314382579052,   866960537634734186,    75437527158751496],
       [   75436444827255052,    72622794571776268,   147495112607006992,
          217862783043109122,   437418788272608264,    72738193867277072],
       [   72628266377019664,  9156383251568132368,    76562301868060416,
         9151454149547000078,   144254903362027264,        6599201675794]])

In [29]:
np.zeros_like(test)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [30]:
# identity
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [31]:
# eye
np.eye(3,5, k=2, dtype=np.int8)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [32]:
# diag
mat = np.arange(9).reshape(3,3)
print(mat)
np.diag(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 4, 8])

In [33]:
print(mat)
np.diag(mat, k=1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([1, 5])

In [34]:
# random sampling
np.random.uniform(0,1,10).reshape(2,5)# 균등분포

array([[0.40878819, 0.75842056, 0.01592504, 0.88720825, 0.29274875],
       [0.00944485, 0.73193902, 0.12349641, 0.93808427, 0.199661  ]])

In [35]:
np.random.normal(0,1,10).reshape(2,5)# 정규분포

array([[ 1.25478918, -1.38058155,  1.26805522,  2.16912375, -0.52433205],
       [ 0.02012885,  1.42018706,  0.45050784, -0.2585435 , -1.729032  ]])

In [36]:
np.random.exponential(scale=2, size=100)

array([3.77684556e-01, 4.84328453e+00, 4.75594970e-01, 1.61917315e+00,
       7.55743054e-01, 1.94229912e+00, 3.55695722e-01, 1.45434300e+00,
       7.34643831e-01, 4.60992750e-01, 1.23636621e-01, 1.23305230e+00,
       2.23665319e-01, 4.86162397e-01, 1.23753408e+00, 4.91237066e+00,
       4.70223079e+00, 1.76232826e+00, 2.30644698e+00, 7.74796801e-02,
       2.94641391e+00, 2.93847946e-01, 1.17888215e+00, 7.72315640e-01,
       3.99482616e+00, 1.88285378e+00, 2.45801571e+00, 1.30234797e+00,
       1.42016559e+00, 1.79795185e+00, 1.93874301e+00, 1.95773344e+00,
       3.93066976e-01, 2.03088601e+00, 1.08019529e+00, 1.70008215e+00,
       5.36927294e-02, 8.33352209e+00, 2.73880974e-01, 2.08035112e-01,
       1.18517977e+00, 4.50077264e+00, 1.77413185e+00, 1.29388824e-01,
       4.78520976e-02, 2.61042655e+00, 2.36053021e+00, 1.09630198e+00,
       1.13566000e+00, 4.29810712e+00, 4.54907903e-01, 4.00406750e+00,
       2.52639166e+00, 1.34391834e+00, 8.44043173e-02, 5.15944446e+00,
      

### Operation Functions

In [37]:
kk = np.arange(1,11)
kk

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
kk.sum(dtype=np.float)

/tmp/ipykernel_1075/736833032.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  kk.sum(dtype=np.float)


55.0

In [39]:
kk.mean()

5.5

In [40]:
# axis : 모든 operation function을 실행할 때 기준이 되는  dimension 축
# axis는 shape 표현시 앞에서부터 번호가 매겨진다.
test = np.arange(1,13).reshape(3,4)
print(test)
print()
print(test.sum(axis=0))
print()
print(test.sum(axis=1))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[15 18 21 24]

[10 26 42]


### Concatenate

In [41]:
# vstack
a = np.array([1,2,3])
b = np.array([5,6,7])
np.vstack((a,b))

array([[1, 2, 3],
       [5, 6, 7]])

In [42]:
# hstack
a = np.array([[1],[2],[3]])
b = np.array([[5],[6],[7]])
np.hstack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7]])

In [43]:
# concatenate
a = np.array([1,2,3])
b = np.array([5,6,7])
np.concatenate((a,b), axis=0)

array([1, 2, 3, 5, 6, 7])

In [44]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[5,6]])
print(a)
print(b)
np.concatenate((a,b.T), axis=1)

[[1 2 3]
 [4 5 6]]
[[5 6]]


array([[1, 2, 3, 5],
       [4, 5, 6, 6]])

### Array Operation

In [45]:
# archimatic operation

a = np.array([[1,2,3], [4,5,6]], float)
a + a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [46]:
a-a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
a*a

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [48]:
# element wise operation
# this is dot product of same shape two array
aa = np.arange(1, 13).reshape(3,4)
aa * aa

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [49]:
test_a = np.arange(1, 7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)
print(test_a)
print(test_b)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [50]:
# dot product
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [51]:
# transpose
print(test_a)
print()
print(test_a.T)
print()
print(test_b)
print()
print(test_b.transpose())

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[ 7  8]
 [ 9 10]
 [11 12]]

[[ 7  9 11]
 [ 8 10 12]]


In [52]:
# broadcasting
# shape이 다른 배열간 연산을 지원
bb = np.array([[1,2,3],[3,4,5]], float)
s = 3 

In [53]:
bb+s

array([[4., 5., 6.],
       [6., 7., 8.]])

In [54]:
bb-s

array([[-2., -1.,  0.],
       [ 0.,  1.,  2.]])

In [55]:
bb*s

array([[ 3.,  6.,  9.],
       [ 9., 12., 15.]])

In [56]:
bb/s

array([[0.33333333, 0.66666667, 1.        ],
       [1.        , 1.33333333, 1.66666667]])

### numpy performance

In [ ]:
def sclar_vector_product(scalar, vector):
    res = []
    for val in vector:
        res.append(scalar*val)
    return res

iternation_max = 100000000

vector = list(range(iternation_max))
scalar = 2

%timeit sclar_vector_product(scalar, vector) #for loop를 이용한 성능


: 

: 

In [ ]:
%timeit [scalar * value for value in range(iternation_max)] # list comprehension을 이용한 성능

In [1]:
%timeit np.arange(iternation_max) * scalar # numpy를 이용한 성능

NameError: name 'np' is not defined

### Comparison

In [57]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
b = a<4
b

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [60]:
np.any(a>5) # any, 하나라도 조건에 만족하면 true

True

In [61]:
np.all(a<3) # all, 모두가 조건에 만족한다면 true

False

In [62]:
a = np.array([1,3,0], float)
b = np.array([5,2,1], float)
a>b

array([False,  True, False])

In [63]:
np.logical_and(a>0, a<3) # and 조건의 condition

array([ True, False, False])

In [64]:
c = np.array([True, False, False], bool)
np.logical_not(c)

array([False,  True,  True])

In [65]:
np.logical_or(a, c)

array([ True,  True, False])

### np.where()

In [67]:
np.where(a>0, 3, 2) # where(condition, True, False)

array([3, 3, 2])

In [68]:
a = np.arange(10)
np.where(a>5) # Index 값 반환

(array([6, 7, 8, 9]),)

In [70]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a) # Not a Number

array([False,  True, False])

In [71]:
np.isfinite(a) # is finite number

array([ True, False, False])

In [72]:
# argmax
# 가장 큰 값의 인덱스
a = np.array([1,2,3,4,5,456,8,6796967,678])
np.argmax(a)

7

In [73]:
np.argmin(a)

0

In [75]:
# axis 기반의 반환
a = np.array([[1,2,4,5], [9,55,622,6], [9,98,2,1]])
print(a)
np.argmax(a, axis=1), np.argmin(a, axis=0)

[[  1   2   4   5]
 [  9  55 622   6]
 [  9  98   2   1]]


(array([3, 2, 1]), array([0, 0, 2, 2]))

In [76]:
 # fancy index
 a = np.array([2,4,6,8], float)
 b = np.array([0,0,1,3,2,1], int) # 반드시 int로 선언
 a[b] # bracket index, b배열의 값을 index로 하여 a의 값을 추출함

array([2., 2., 4., 8., 6., 4.])

In [78]:
a.take(b) # take함수 : bracket index와 같은 효과

array([2., 2., 4., 8., 6., 4.])

### Numpy Data IO

In [ ]:
a = np.loadtxt("./~~~~~~~~.txt")
a[:10]

In [79]:
a_int = a.astype(int)
a_int[:3]

array([2, 4, 6])

In [80]:
np.savetxt('./assets/numpy01/int_data.csv', a_int, delimiter=",")

In [81]:
np.save("./assets/numpy01/npy_test_obj", arr=a_int)

In [82]:
a_test = np.load(file="./assets/numpy01/npy_test_obj.npy")
a_test

array([2, 4, 6, 8])