# PyTorch Basic

numpy + AutoGrad(자동미분)

In [1]:
import numpy as np
import torch

In [2]:
# numpy - ndarray
n_array = np.arange(10).reshape(5,2)
print(n_array)
print(f"ndim : {n_array.ndim}, shape : {n_array.shape}")
n_array = np.arange(10).reshape(2,5)
print(n_array)
print(f"ndim : {n_array.ndim}, shape : {n_array.shape}")

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
ndim : 2, shape : (5, 2)
[[0 1 2 3 4]
 [5 6 7 8 9]]
ndim : 2, shape : (2, 5)


In [3]:
t_array = torch.FloatTensor(n_array)
print(t_array)
print(f"ndim : {t_array.ndim}, shape : {t_array.shape}")

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
ndim : 2, shape : torch.Size([2, 5])


In [4]:
data = [[3, 5],[10, 5]]
x_data = torch.tensor(data)
x_data

tensor([[ 3,  5],
        [10,  5]])

In [5]:
nd_array_ex = np.array(data)
tensor_array = torch.from_numpy(nd_array_ex)
tensor_array

tensor([[ 3,  5],
        [10,  5]])

In [6]:
data = [[3,5,20], [10,5,50], [1,5,10]]
x_data = torch.tensor(data)

print(f"x_data[1:] : {x_data[1:]}")
print(f"x_data[:2, 1:] : {x_data[:2, 1:]}")
print(f"x_data.flatten : {x_data.flatten}")
print(f"torch.ones_like : {torch.ones_like(x_data)}")
print(f"x_data.numpy() : {x_data.numpy()}")
print(f"x_data.shape : {x_data.shape}")
print(f"x_data.dtype : {x_data.dtype}")

x_data[1:] : tensor([[10,  5, 50],
        [ 1,  5, 10]])
x_data[:2, 1:] : tensor([[ 5, 20],
        [ 5, 50]])
x_data.flatten : <built-in method flatten of Tensor object at 0x7fa442542310>
torch.ones_like : tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
x_data.numpy() : [[ 3  5 20]
 [10  5 50]
 [ 1  5 10]]
x_data.shape : torch.Size([3, 3])
x_data.dtype : torch.int64


In [7]:
x_data.device

device(type='cpu')

In [8]:
if torch.cuda.is_available():
    x_data_cuda = x_data.to('cuda')
    print(x_data_cuda.device)

cuda:0


In [9]:
# View : reshape과 동일하게 tensor의 shape을 변환
# squeeze : 차원의 개수가 1인 차원을 삭체(압축)
# unsqueeze : 차원의 개수가 1인 차원을 추가

tensor_ex  = torch.rand(size=(2,3,2))
tensor_ex

tensor([[[0.9134, 0.9175],
         [0.0980, 0.9036],
         [0.7378, 0.0250]],

        [[0.8870, 0.2826],
         [0.7000, 0.9605],
         [0.7792, 0.1040]]])

In [10]:
tensor_ex.view([-1, 6])

tensor([[0.9134, 0.9175, 0.0980, 0.9036, 0.7378, 0.0250],
        [0.8870, 0.2826, 0.7000, 0.9605, 0.7792, 0.1040]])

In [11]:
tensor_ex.reshape([-1, 6])

tensor([[0.9134, 0.9175, 0.0980, 0.9036, 0.7378, 0.0250],
        [0.8870, 0.2826, 0.7000, 0.9605, 0.7792, 0.1040]])

In [12]:
a = torch.zeros(3,2)
b = a.view(2,3)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [13]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [14]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [15]:
a = torch.zeros(3,2)
b = a.t().reshape(6)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [16]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [17]:
b

tensor([0., 0., 0., 0., 0., 0.])

In [25]:
tensor_ex = torch.rand(size=(2,1,2))
tensor_ex.squeeze()

tensor([[0.8416, 0.0361],
        [0.9456, 0.9947]])

In [28]:
tensor_ex = torch.rand(size=(2,2))
print(tensor_ex.unsqueeze(0).shape)
print(tensor_ex.unsqueeze(0))

torch.Size([1, 2, 2])
tensor([[[0.7260, 0.9364],
         [0.3003, 0.6304]]])


In [29]:
print(tensor_ex.unsqueeze(1).shape)
print(tensor_ex.unsqueeze(1))

torch.Size([2, 1, 2])
tensor([[[0.7260, 0.9364]],

        [[0.3003, 0.6304]]])


In [30]:
print(tensor_ex.unsqueeze(2).shape)
print(tensor_ex.unsqueeze(2))

torch.Size([2, 2, 1])
tensor([[[0.7260],
         [0.9364]],

        [[0.3003],
         [0.6304]]])


In [31]:
n1 = np.arange(10).reshape(2,5)
t1 = torch.FloatTensor(n1)

In [32]:
n2 = np.arange(10).reshape(5,2)
t2 = torch.FloatTensor(n2)

t1.mm(t2)#내적, dot product

tensor([[ 60.,  70.],
        [160., 195.]])

In [33]:
t1.dot(t2)

RuntimeError: ignored

In [34]:
t1.matmul(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [35]:
import torch.nn.functional as F

tensor = torch.FloatTensor([0.5, 0.7, 0.1])
h_tensor = F.softmax(tensor, dim=0)
h_tensor

tensor([0.3458, 0.4224, 0.2318])

In [36]:
y = torch.randint(5, (10,5))
y_label = y.argmax(dim=1)
y_label

tensor([2, 0, 3, 2, 2, 2, 2, 0, 0, 0])

In [38]:
F.one_hot(y_label)

tensor([[0, 0, 1, 0],
        [1, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0]])

In [39]:
# PyTorch의 핵심은 자동 미분
w = torch.tensor(2.0, requires_grad=True)
y = w**2 # y = w^2
z = 10*y + 24 # z = 10*y + 25
z.backward() # z' = 20w (미분)
w.grad # w = tensor(2.) * 20 = tensor(40.)

tensor(40.)

In [40]:
# 벡터 편미분

a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

Q = 3*a**3 - b**2
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

# Q'/a' = 9 * a**2
a.grad

tensor([36., 81.])

In [41]:
# Q'/b' = -2b
b.grad

tensor([-12.,  -8.])